# 用于存储平衡常数的 toml 文件
# [[K]] 代表平衡常数，每有一个 [[K]] 就代表有一个平衡常数
# value 是 K 的一个属性，代表平衡常数的具体值，一般都是用科学计数法表示，例如 1.3E-1，代表 1.3 × 10^-1
[[K]]
value = 1.3E-1
[[K]]
value = 2.5E-2
[[K]]
value = 1.0E-2
[[K]]
value = 2.14E-3
[[K]]
value = 6.92E-7
[[K]]
value = 5.50E-11